# Generated by Django 4.1.2 on 2023-08-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='preview_url',
        ),
    ]
