# Generated by Django 4.1.2 on 2023-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_song_preview_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.TextField(max_length=500)),
                ('user', models.TextField(max_length=150)),
                ('img_url', models.TextField(max_length=500)),
                ('name', models.TextField(max_length=150)),
            ],
        ),
    ]
