# Generated by Django 4.1.2 on 2023-08-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.TextField(max_length=500)),
                ('user', models.TextField(max_length=150)),
                ('img_url', models.TextField(max_length=500)),
                ('title', models.TextField(max_length=150)),
                ('name', models.TextField(max_length=150)),
            ],
        ),
    ]
